networks:
  chord_net:
    driver: bridge

services:

  chord-node-1:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: chord-node-1
    hostname: chord-node-1
    command: ["create"]
    volumes:
      - ./netmiko-runner.py:/opt/automation/netmiko-runner.py:ro
      - ./config-node1.yaml:/app/config.yaml:ro
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    networks:
      - chord_net
    ports:
      - "8000:8000"   # para poder usar client/chord desde la VM (fuera de Docker)
    ulimits:
      nproc:
        soft: 4096
        hard: 4096
    restart: "no"

  chord-node-2:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: chord-node-2
    hostname: chord-node-2
    command: ["join", "chord-node-1", "8000"]
    volumes:
      - ./netmiko-runner.py:/opt/automation/netmiko-runner.py:ro
      - ./config-node2.yaml:/app/config.yaml:ro
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    networks:
      - chord_net
    depends_on:
      - chord-node-1
    ulimits:
      nproc:
        soft: 4096
        hard: 4096
    restart: "no"

  chord-node-3:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: chord-node-3
    hostname: chord-node-3
    command: ["join", "chord-node-1", "8000"]
    volumes:
      - ./netmiko-runner.py:/opt/automation/netmiko-runner.py:ro
      - ./config-node3.yaml:/app/config.yaml:ro
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    networks:
      - chord_net
    depends_on:
      - chord-node-1
    ulimits:
      nproc:
        soft: 4096
        hard: 4096
    restart: "no"