// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: chord.proto

package chordpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chord_FindSuccessor_FullMethodName      = "/chord.chord/FindSuccessor"
	Chord_GetPredecessor_FullMethodName     = "/chord.chord/GetPredecessor"
	Chord_Notify_FullMethodName             = "/chord.chord/Notify"
	Chord_CheckPredecessor_FullMethodName   = "/chord.chord/CheckPredecessor"
	Chord_GetSuccessorList_FullMethodName   = "/chord.chord/GetSuccessorList"
	Chord_RecvCoordinatorMsg_FullMethodName = "/chord.chord/RecvCoordinatorMsg"
	Chord_GetKeys_FullMethodName            = "/chord.chord/GetKeys"
	Chord_SendReplicas_FullMethodName       = "/chord.chord/SendReplicas"
	Chord_RemoveReplicas_FullMethodName     = "/chord.chord/RemoveReplicas"
	Chord_Get_FullMethodName                = "/chord.chord/Get"
	Chord_Put_FullMethodName                = "/chord.chord/Put"
	Chord_Locate_FullMethodName             = "/chord.chord/Locate"
	Chord_Run_FullMethodName                = "/chord.chord/Run"
)

// ChordClient is the client API for Chord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChordClient interface {
	// Find the successor of the given ID
	FindSuccessor(ctx context.Context, in *PeerID, opts ...grpc.CallOption) (*Node, error)
	// Get the current predecessor of a node
	GetPredecessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Node, error)
	// A Node thinks it is our predecessor and it is notifying us!
	Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Empty, error)
	// Check if predecessor is still alive
	CheckPredecessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Get successor list of a node
	GetSuccessorList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SuccessorList, error)
	// TODO: consider changing the names of the below RPCs for replicas. They are not very clear
	// Receive coordinator messages from nodes who are the coordinators
	// for replica groups around the chord ring
	RecvCoordinatorMsg(ctx context.Context, in *CoordinatorMsg, opts ...grpc.CallOption) (*Empty, error)
	// Get keys we are responsible for from a node (typically a new node calls this on their successor)
	GetKeys(ctx context.Context, in *PeerID, opts ...grpc.CallOption) (*KVs, error)
	// Receive replica KV pairs from the leader of the replica group
	SendReplicas(ctx context.Context, in *ReplicaMsg, opts ...grpc.CallOption) (*Empty, error)
	// Remove replica KV pairs
	RemoveReplicas(ctx context.Context, in *ReplicaMsg, opts ...grpc.CallOption) (*Empty, error)
	// Get a value
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error)
	// Create a new key-value pair
	Put(ctx context.Context, in *KV, opts ...grpc.CallOption) (*Empty, error)
	// Locate the node containing a key
	Locate(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Node, error)
	// Run a read-only command against the device identified by kv.key (host/IP),
	// executing kv.value (the command) on whichever node owns that key.
	Run(ctx context.Context, in *KV, opts ...grpc.CallOption) (*Value, error)
}

type chordClient struct {
	cc grpc.ClientConnInterface
}

func NewChordClient(cc grpc.ClientConnInterface) ChordClient {
	return &chordClient{cc}
}

func (c *chordClient) FindSuccessor(ctx context.Context, in *PeerID, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, Chord_FindSuccessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetPredecessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, Chord_GetPredecessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chord_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) CheckPredecessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chord_CheckPredecessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetSuccessorList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SuccessorList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessorList)
	err := c.cc.Invoke(ctx, Chord_GetSuccessorList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) RecvCoordinatorMsg(ctx context.Context, in *CoordinatorMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chord_RecvCoordinatorMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetKeys(ctx context.Context, in *PeerID, opts ...grpc.CallOption) (*KVs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVs)
	err := c.cc.Invoke(ctx, Chord_GetKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) SendReplicas(ctx context.Context, in *ReplicaMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chord_SendReplicas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) RemoveReplicas(ctx context.Context, in *ReplicaMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chord_RemoveReplicas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Value)
	err := c.cc.Invoke(ctx, Chord_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Put(ctx context.Context, in *KV, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chord_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Locate(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, Chord_Locate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Run(ctx context.Context, in *KV, opts ...grpc.CallOption) (*Value, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Value)
	err := c.cc.Invoke(ctx, Chord_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChordServer is the server API for Chord service.
// All implementations must embed UnimplementedChordServer
// for forward compatibility.
type ChordServer interface {
	// Find the successor of the given ID
	FindSuccessor(context.Context, *PeerID) (*Node, error)
	// Get the current predecessor of a node
	GetPredecessor(context.Context, *Empty) (*Node, error)
	// A Node thinks it is our predecessor and it is notifying us!
	Notify(context.Context, *Node) (*Empty, error)
	// Check if predecessor is still alive
	CheckPredecessor(context.Context, *Empty) (*Empty, error)
	// Get successor list of a node
	GetSuccessorList(context.Context, *Empty) (*SuccessorList, error)
	// TODO: consider changing the names of the below RPCs for replicas. They are not very clear
	// Receive coordinator messages from nodes who are the coordinators
	// for replica groups around the chord ring
	RecvCoordinatorMsg(context.Context, *CoordinatorMsg) (*Empty, error)
	// Get keys we are responsible for from a node (typically a new node calls this on their successor)
	GetKeys(context.Context, *PeerID) (*KVs, error)
	// Receive replica KV pairs from the leader of the replica group
	SendReplicas(context.Context, *ReplicaMsg) (*Empty, error)
	// Remove replica KV pairs
	RemoveReplicas(context.Context, *ReplicaMsg) (*Empty, error)
	// Get a value
	Get(context.Context, *Key) (*Value, error)
	// Create a new key-value pair
	Put(context.Context, *KV) (*Empty, error)
	// Locate the node containing a key
	Locate(context.Context, *Key) (*Node, error)
	// Run a read-only command against the device identified by kv.key (host/IP),
	// executing kv.value (the command) on whichever node owns that key.
	Run(context.Context, *KV) (*Value, error)
	mustEmbedUnimplementedChordServer()
}

// UnimplementedChordServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChordServer struct{}

func (UnimplementedChordServer) FindSuccessor(context.Context, *PeerID) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method FindSuccessor not implemented")
}
func (UnimplementedChordServer) GetPredecessor(context.Context, *Empty) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPredecessor not implemented")
}
func (UnimplementedChordServer) Notify(context.Context, *Node) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedChordServer) CheckPredecessor(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPredecessor not implemented")
}
func (UnimplementedChordServer) GetSuccessorList(context.Context, *Empty) (*SuccessorList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSuccessorList not implemented")
}
func (UnimplementedChordServer) RecvCoordinatorMsg(context.Context, *CoordinatorMsg) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecvCoordinatorMsg not implemented")
}
func (UnimplementedChordServer) GetKeys(context.Context, *PeerID) (*KVs, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeys not implemented")
}
func (UnimplementedChordServer) SendReplicas(context.Context, *ReplicaMsg) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendReplicas not implemented")
}
func (UnimplementedChordServer) RemoveReplicas(context.Context, *ReplicaMsg) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveReplicas not implemented")
}
func (UnimplementedChordServer) Get(context.Context, *Key) (*Value, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedChordServer) Put(context.Context, *KV) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedChordServer) Locate(context.Context, *Key) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method Locate not implemented")
}
func (UnimplementedChordServer) Run(context.Context, *KV) (*Value, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedChordServer) mustEmbedUnimplementedChordServer() {}
func (UnimplementedChordServer) testEmbeddedByValue()               {}

// UnsafeChordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChordServer will
// result in compilation errors.
type UnsafeChordServer interface {
	mustEmbedUnimplementedChordServer()
}

func RegisterChordServer(s grpc.ServiceRegistrar, srv ChordServer) {
	// If the following call panics, it indicates UnimplementedChordServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chord_ServiceDesc, srv)
}

func _Chord_FindSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).FindSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_FindSuccessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).FindSuccessor(ctx, req.(*PeerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_GetPredecessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetPredecessor(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Notify(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_CheckPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).CheckPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_CheckPredecessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).CheckPredecessor(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetSuccessorList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetSuccessorList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_GetSuccessorList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetSuccessorList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_RecvCoordinatorMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).RecvCoordinatorMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_RecvCoordinatorMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).RecvCoordinatorMsg(ctx, req.(*CoordinatorMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_GetKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetKeys(ctx, req.(*PeerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_SendReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).SendReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_SendReplicas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).SendReplicas(ctx, req.(*ReplicaMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_RemoveReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).RemoveReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_RemoveReplicas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).RemoveReplicas(ctx, req.(*ReplicaMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KV)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Put(ctx, req.(*KV))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Locate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Locate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_Locate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Locate(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KV)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chord_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Run(ctx, req.(*KV))
	}
	return interceptor(ctx, in, info, handler)
}

// Chord_ServiceDesc is the grpc.ServiceDesc for Chord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chord.chord",
	HandlerType: (*ChordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindSuccessor",
			Handler:    _Chord_FindSuccessor_Handler,
		},
		{
			MethodName: "GetPredecessor",
			Handler:    _Chord_GetPredecessor_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _Chord_Notify_Handler,
		},
		{
			MethodName: "CheckPredecessor",
			Handler:    _Chord_CheckPredecessor_Handler,
		},
		{
			MethodName: "GetSuccessorList",
			Handler:    _Chord_GetSuccessorList_Handler,
		},
		{
			MethodName: "RecvCoordinatorMsg",
			Handler:    _Chord_RecvCoordinatorMsg_Handler,
		},
		{
			MethodName: "GetKeys",
			Handler:    _Chord_GetKeys_Handler,
		},
		{
			MethodName: "SendReplicas",
			Handler:    _Chord_SendReplicas_Handler,
		},
		{
			MethodName: "RemoveReplicas",
			Handler:    _Chord_RemoveReplicas_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Chord_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Chord_Put_Handler,
		},
		{
			MethodName: "Locate",
			Handler:    _Chord_Locate_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _Chord_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chord.proto",
}
