// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: chord.proto

package chordpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_chord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{0}
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_chord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Node) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Node) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type SuccessorList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successors    []*Node                `protobuf:"bytes,1,rep,name=successors,proto3" json:"successors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessorList) Reset() {
	*x = SuccessorList{}
	mi := &file_chord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessorList) ProtoMessage() {}

func (x *SuccessorList) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessorList.ProtoReflect.Descriptor instead.
func (*SuccessorList) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{2}
}

func (x *SuccessorList) GetSuccessors() []*Node {
	if x != nil {
		return x.Successors
	}
	return nil
}

type CoordinatorMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldLeaderId   []byte                 `protobuf:"bytes,1,opt,name=oldLeaderId,proto3" json:"oldLeaderId,omitempty"`
	NewLeaderId   []byte                 `protobuf:"bytes,2,opt,name=newLeaderId,proto3" json:"newLeaderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMsg) Reset() {
	*x = CoordinatorMsg{}
	mi := &file_chord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMsg) ProtoMessage() {}

func (x *CoordinatorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMsg.ProtoReflect.Descriptor instead.
func (*CoordinatorMsg) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{3}
}

func (x *CoordinatorMsg) GetOldLeaderId() []byte {
	if x != nil {
		return x.OldLeaderId
	}
	return nil
}

func (x *CoordinatorMsg) GetNewLeaderId() []byte {
	if x != nil {
		return x.NewLeaderId
	}
	return nil
}

type ReplicaMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      []byte                 `protobuf:"bytes,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	Kv            []*KV                  `protobuf:"bytes,2,rep,name=kv,proto3" json:"kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaMsg) Reset() {
	*x = ReplicaMsg{}
	mi := &file_chord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaMsg) ProtoMessage() {}

func (x *ReplicaMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaMsg.ProtoReflect.Descriptor instead.
func (*ReplicaMsg) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicaMsg) GetLeaderId() []byte {
	if x != nil {
		return x.LeaderId
	}
	return nil
}

func (x *ReplicaMsg) GetKv() []*KV {
	if x != nil {
		return x.Kv
	}
	return nil
}

type PeerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerID) Reset() {
	*x = PeerID{}
	mi := &file_chord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerID) ProtoMessage() {}

func (x *PeerID) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerID.ProtoReflect.Descriptor instead.
func (*PeerID) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{5}
}

func (x *PeerID) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_chord_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{6}
}

func (x *Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_chord_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{7}
}

func (x *Value) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV) Reset() {
	*x = KV{}
	mi := &file_chord_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{8}
}

func (x *KV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KV) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KVs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kvs           []*KV                  `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVs) Reset() {
	*x = KVs{}
	mi := &file_chord_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVs) ProtoMessage() {}

func (x *KVs) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVs.ProtoReflect.Descriptor instead.
func (*KVs) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{9}
}

func (x *KVs) GetKvs() []*KV {
	if x != nil {
		return x.Kvs
	}
	return nil
}

var File_chord_proto protoreflect.FileDescriptor

const file_chord_proto_rawDesc = "" +
	"\n" +
	"\vchord.proto\x12\x05chord\"\a\n" +
	"\x05empty\">\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"<\n" +
	"\rSuccessorList\x12+\n" +
	"\n" +
	"successors\x18\x01 \x03(\v2\v.chord.NodeR\n" +
	"successors\"T\n" +
	"\x0eCoordinatorMsg\x12 \n" +
	"\voldLeaderId\x18\x01 \x01(\fR\voldLeaderId\x12 \n" +
	"\vnewLeaderId\x18\x02 \x01(\fR\vnewLeaderId\"C\n" +
	"\n" +
	"ReplicaMsg\x12\x1a\n" +
	"\bleaderId\x18\x01 \x01(\fR\bleaderId\x12\x19\n" +
	"\x02kv\x18\x02 \x03(\v2\t.chord.KVR\x02kv\"\x18\n" +
	"\x06PeerID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\x17\n" +
	"\x03Key\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x1d\n" +
	"\x05Value\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\",\n" +
	"\x02KV\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\"\n" +
	"\x03KVs\x12\x1b\n" +
	"\x03kvs\x18\x01 \x03(\v2\t.chord.KVR\x03kvs2\xd1\x04\n" +
	"\x05chord\x12-\n" +
	"\rFindSuccessor\x12\r.chord.PeerID\x1a\v.chord.Node\"\x00\x12-\n" +
	"\x0eGetPredecessor\x12\f.chord.empty\x1a\v.chord.Node\"\x00\x12%\n" +
	"\x06Notify\x12\v.chord.Node\x1a\f.chord.empty\"\x00\x120\n" +
	"\x10CheckPredecessor\x12\f.chord.empty\x1a\f.chord.empty\"\x00\x128\n" +
	"\x10GetSuccessorList\x12\f.chord.empty\x1a\x14.chord.SuccessorList\"\x00\x12;\n" +
	"\x12RecvCoordinatorMsg\x12\x15.chord.CoordinatorMsg\x1a\f.chord.empty\"\x00\x12&\n" +
	"\aGetKeys\x12\r.chord.PeerID\x1a\n" +
	".chord.KVs\"\x00\x121\n" +
	"\fSendReplicas\x12\x11.chord.ReplicaMsg\x1a\f.chord.empty\"\x00\x123\n" +
	"\x0eRemoveReplicas\x12\x11.chord.ReplicaMsg\x1a\f.chord.empty\"\x00\x12!\n" +
	"\x03Get\x12\n" +
	".chord.Key\x1a\f.chord.Value\"\x00\x12 \n" +
	"\x03Put\x12\t.chord.KV\x1a\f.chord.empty\"\x00\x12#\n" +
	"\x06Locate\x12\n" +
	".chord.Key\x1a\v.chord.Node\"\x00\x12 \n" +
	"\x03Run\x12\t.chord.KV\x1a\f.chord.Value\"\x00B&Z$github.com/cdesiniotis/chord/chordpbb\x06proto3"

var (
	file_chord_proto_rawDescOnce sync.Once
	file_chord_proto_rawDescData []byte
)

func file_chord_proto_rawDescGZIP() []byte {
	file_chord_proto_rawDescOnce.Do(func() {
		file_chord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chord_proto_rawDesc), len(file_chord_proto_rawDesc)))
	})
	return file_chord_proto_rawDescData
}

var file_chord_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chord_proto_goTypes = []any{
	(*Empty)(nil),          // 0: chord.empty
	(*Node)(nil),           // 1: chord.Node
	(*SuccessorList)(nil),  // 2: chord.SuccessorList
	(*CoordinatorMsg)(nil), // 3: chord.CoordinatorMsg
	(*ReplicaMsg)(nil),     // 4: chord.ReplicaMsg
	(*PeerID)(nil),         // 5: chord.PeerID
	(*Key)(nil),            // 6: chord.Key
	(*Value)(nil),          // 7: chord.Value
	(*KV)(nil),             // 8: chord.KV
	(*KVs)(nil),            // 9: chord.KVs
}
var file_chord_proto_depIdxs = []int32{
	1,  // 0: chord.SuccessorList.successors:type_name -> chord.Node
	8,  // 1: chord.ReplicaMsg.kv:type_name -> chord.KV
	8,  // 2: chord.KVs.kvs:type_name -> chord.KV
	5,  // 3: chord.chord.FindSuccessor:input_type -> chord.PeerID
	0,  // 4: chord.chord.GetPredecessor:input_type -> chord.empty
	1,  // 5: chord.chord.Notify:input_type -> chord.Node
	0,  // 6: chord.chord.CheckPredecessor:input_type -> chord.empty
	0,  // 7: chord.chord.GetSuccessorList:input_type -> chord.empty
	3,  // 8: chord.chord.RecvCoordinatorMsg:input_type -> chord.CoordinatorMsg
	5,  // 9: chord.chord.GetKeys:input_type -> chord.PeerID
	4,  // 10: chord.chord.SendReplicas:input_type -> chord.ReplicaMsg
	4,  // 11: chord.chord.RemoveReplicas:input_type -> chord.ReplicaMsg
	6,  // 12: chord.chord.Get:input_type -> chord.Key
	8,  // 13: chord.chord.Put:input_type -> chord.KV
	6,  // 14: chord.chord.Locate:input_type -> chord.Key
	8,  // 15: chord.chord.Run:input_type -> chord.KV
	1,  // 16: chord.chord.FindSuccessor:output_type -> chord.Node
	1,  // 17: chord.chord.GetPredecessor:output_type -> chord.Node
	0,  // 18: chord.chord.Notify:output_type -> chord.empty
	0,  // 19: chord.chord.CheckPredecessor:output_type -> chord.empty
	2,  // 20: chord.chord.GetSuccessorList:output_type -> chord.SuccessorList
	0,  // 21: chord.chord.RecvCoordinatorMsg:output_type -> chord.empty
	9,  // 22: chord.chord.GetKeys:output_type -> chord.KVs
	0,  // 23: chord.chord.SendReplicas:output_type -> chord.empty
	0,  // 24: chord.chord.RemoveReplicas:output_type -> chord.empty
	7,  // 25: chord.chord.Get:output_type -> chord.Value
	0,  // 26: chord.chord.Put:output_type -> chord.empty
	1,  // 27: chord.chord.Locate:output_type -> chord.Node
	7,  // 28: chord.chord.Run:output_type -> chord.Value
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chord_proto_init() }
func file_chord_proto_init() {
	if File_chord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chord_proto_rawDesc), len(file_chord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chord_proto_goTypes,
		DependencyIndexes: file_chord_proto_depIdxs,
		MessageInfos:      file_chord_proto_msgTypes,
	}.Build()
	File_chord_proto = out.File
	file_chord_proto_goTypes = nil
	file_chord_proto_depIdxs = nil
}
